# Data Exploration of Stress Analysis in Social Media

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# read the csv dataset
tips_data = pd.read_csv('tips.csv')

In [ ]:
# show the data of csv file
tips_data

     total_bill   tip   sex   smoker  day    time   size
0       16.99    1.01  Female    No    Sun  Dinner    2
1       10.34    1.66    Male    No    Sun  Dinner    3
2       21.01    3.50    Male    No    Sun  Dinner    3
3       23.68    3.31    Male    No    Sun  Dinner    2
4       24.59    3.61  Female    No    Sun  Dinner    4
..          ...   ...     ...    ...   ...     ...   ...
239     29.03    5.92    Male    No    Sat  Dinner    3
240     27.18    2.00  Female   Yes    Sat  Dinner    2
241     22.67    2.00    Male   Yes    Sat  Dinner    2
242     17.82    1.75    Male    No    Sat  Dinner    2
243     18.78    3.00  Female    No   Thur  Dinner    2

[244 rows x 7 columns]

In [ ]:
# total rows value and columns value
tips_data.shape

(244, 7)

In [ ]:
# show columns name
tips_data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [19]:
# show the top 5 data of file
tips_data.head()

   total_bill   tip   sex   smoker day    time   size
0     16.99    1.01  Female   No    Sun  Dinner    2
1     10.34    1.66    Male   No    Sun  Dinner    3
2     21.01    3.50    Male   No    Sun  Dinner    3
3     23.68    3.31    Male   No    Sun  Dinner    2
4     24.59    3.61  Female   No    Sun  Dinner    4

In [ ]:
# gives a statistical summary of your dataset columns.
tips_data.describe()

       total_bill      tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

# std (standard deviation)

Measures how spread out values are.

- small std → values are close together
- large std → values vary a lot

In [ ]:
# This actually runs the function and displays dataframe information.
tips_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [ ]:
# show the data types of every columns data
tips_data.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [ ]:
# checks how many missing (NaN) values exist in each column.
tips_data.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
# counts how many times each unique value appears in the sex column.
tips_data.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
# to show the unique data in required column
unique_values = tips_data.day.unique()
unique_values

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [31]:
smoker_values = tips_data[['smoker','sex']].value_counts()
smoker_values

smoker  sex
No      Male      97
Yes     Male      60
No      Female    54
Yes     Female    33
Name: count, dtype: int64

In [32]:
smoker_ratio = (
    tips_data[tips_data['smoker'] == 'Yes']['sex'].value_counts(normalize=True) * 100
)
smoker_ratio

sex
Male      64.516129
Female    35.483871
Name: proportion, dtype: float64

There are male smoker ratio is much higher than female.

In [33]:
grouped_data = tips_data.groupby(['sex', 'smoker'])

In [35]:
grouped_data[['tip', 'total_bill']].mean()

                  tip    total_bill
sex    smoker
Female No      2.773519   18.105185
       Yes     2.931515   17.977879
Male   No      3.113402   19.791237
       Yes     3.051167   22.284500

Here we can clearly see the data of tip and total bill is much more spend male than female.

In [36]:
tips_data[['tip', 'total_bill']].corr()

               tip    total_bill
tip         1.000000   0.675734
total_bill  0.675734   1.000000

#### Use correlation when you want to measure the relationship between two numeric variables.

It helps answer questions like:

- “When one variable increases, does another also increase?”
- “Are these variables related?”
- “How strongly are they connected?”

--> As bill increases, tip also increases.

---> That creates positive correlation.

So customers with larger bills tend to give larger tips.